services:
  tournament-server:
    build: .
    container_name: brackets-manager-api
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_FILE=data/db.json
    restart: unless-stopped
