services:
  tournament-server:
    image: ghcr.io/juniornff/brackets-manager-server:latest
    container_name: brackets-manager-api
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - API_KEY=${API_KEY}
      - DATA_FILE=db.json
      - VERBOSE=false
    restart: unless-stopped
